### PR TITLE
Type validation for model parameters

### PR DESCRIPTION
**Pull request by svilupp**
Fixes https://github.com/Evovest/EvoTrees.jl/issues/222

An initial proposal to validate whether this design is acceptable.
- Restricts the following parameters: `nbins` (to UInt8)
- Adds a function to convert safely (`convert_parameter`) with an understandable error for the user (see example below)

MWE:
```
config = EvoTreeClassifier(nbins=255)
# works fine

config = EvoTreeClassifier(nbins=256)
# ERROR: Invalid value for parameter `nbins`: 256. `nbins` must be of type UInt8 (ie, value between 0 and 255).
```

Question:
- Are there more parameters that should be more restrictive? So far I've restricted only `nbins` to UInt8

TODO:
- corresponding tests once we agree on the approach

### CODE REVIEW

**Comment by jeremiedb** [comment]
I like the detailed error message. 
Chaging the type of the the `struct` such as `EvoTreeRegressor` would however in a braking change. As such, I'd favor instead a mechanism based on the parameter domain rather their their type. For example, let the `nbins` as a Int, but rather check that it's value is [2-255]. 

The other checks would include:
- nrounds >= 0
- eta >= 0
- lambda >= 0
- gamma >= 0
- alpha [0-1]
- max_depth >= 1
- min_weight >= 0
- rowsample/colsample ]0, 1]

Let me know if you want to pursue in that direction, or I can follow up on this.

**Comment by svilupp** [comment]
I've updated the implementation only for EvoTreeRegressor to sense-check if that's what you were thinking.

I created a dedicated function to avoid copy-paste errors `check_args` that can be simply called in each kwarg constructor before instantiating the model struct.

Is this closer to what you had in mind?

**Comment by svilupp** [comment]
> Changing the type of the struct such as EvoTreeRegressor would however in a breaking change. 

Just out of curiosity - is it a breaking change if, implicitly, it was always UInt8? 
Ie, any inconsistent number format (that cannot be converted into UInt8) would throw an error.

**Comment by jeremiedb** [comment]
I think the `check_parameter` / `check_args` is a very clean approach! I'm good moving foward with it for all the constructors (Count, Classifier...). As a possible extra, it could be nice to have a `check_args` that acts on the `EvoTreeRegressor` & cie. ni addition to the args `Dict` as in its current form. That would be convenient for applications like in MLJ where the arguments can be mutated so that hyper-params can be reassessed following such mutation. 

Regardng the breaking change of `UInt8`, it would likely be transparent for most users, but I think it should brake a situation where a `EvoTreeRegressor` was saved through serialization. I haven't testetd, but I suspect it would fail to load if the original object was saved as an Int, while the current `struct` is defined as a `UInt8`.

**Comment by ablaom** [comment]
In MLJ parameter checks are implemented by overloaded the `clean!` method. This method is called in MLJ whenever you fit a machine to check users has not mutated the model in a way that is not allowed.

I you use the `@mlj_model` macro (can't remember if this is used here) then that automatically overloads `clean!` for you.

See [here](https://alan-turing-institute.github.io/MLJ.jl/dev/adding_models_for_general_use/#New-model-type-declarations-and-optional-clean!-method), and, for the macro, [here](https://alan-turing-institute.github.io/MLJ.jl/dev/adding_models_for_general_use/#Macro-shortcut).

**Comment by svilupp** [comment]
Thank you for sharing the examples!

Sorry for the long pause, got overwhelmed by work & life :) But I want to close this now.

After having looked through the example of `clean!` method and how it's applied, it seems to be different from our current approach:
- It instantiates the model first
- Then it forces the parameters to their allowed ranges
- It produces a `@warn` log
Basically, as the name suggests, it "cleans it" :)

Whereas `check_args()` checks the type and range before we instantiate the model, and throws an error if it's not acceptable. 
So on one hand, in cases when a model cannot be instantiated, we catch this and provide more helpful error.
On the other hand, the user must fix the error, whereas `clean!` does it under the hood (so the user might not even find out if the logging is disabled)

**Potential Options**
1) keep `check_args()` which will be called on every kwarg construction
2) replace `check_args()` with `MMI.clean!` method inside the kwarg constructors, drop the type check, check only the value range and embrace the `@warn` + "auto-fix" paradigm (minor: would require breaking the separation of MLJ code and model definitions)
3) use `@mlj_model` macro for the structs to define param ranges

I think the last one is out of the question given the discussion in other PRs (backward compatibility).

The choice between 1) and 2) is a bit philosophical. @jeremiedb , do you have a preference?

I personally prefer 1) because it's more explicit and fails on a mistake, but I appreciate that `clean!` is consistent with the rest of MLJ world (although not every model has it). There could also be some hybrids (throw an error instead of auto-fixing etc., it depends on what behaviour we desire)

**Comment by jeremiedb** [comment]
Thanks for looking back into this! 
I'd also favor going with 1 for now. I think it covers the spirit of `clean!` for having sanity check of the hyper params while avoiding taking initiave for a substitute. I prefer treatning improper input values as domain error and as such, returns an error and let the users figure out what's the proper fix for their use case. 

For `eta`, I agree it should be structly positive. 

Regarding: 
> it feels like the models should be validated when constructing directly (via args, not kwargs)

Would you have an example of what you'd have in mind?

Let me know if you need any further clarification.

**Comment by svilupp** [comment]
I've implemented the following changes:
- eta > 0
- nrounds >= 1 (not specified, but it's implicit given the fit_evotree training loop)
- added tests for the checking functionality itself, checking upon construction and checking a model (eg, after a mutation)
- Checking after mutation is done only manually, ie, I have not overloaded the setter
- Updated docs with the implemented parameter value limits
- fixed a few typos that I spotted

Tests pass locally. PR should be ready for review.

**Comment by jeremiedb** [comment]
This looks good to go now, I'll push a patch release. Thanks for your contribution!

**Pull request merged**
