### PR TITLE
Add `ntree_limit` for predict

### LINKED ISSUE #178: Plot loss curve history for train and eval data set
is the way to go "fit" for 1 round manually ?....

### PR DESCRIPTION
**Pull request by Moelf**
close #178

### CODE REVIEW

**Comment by Moelf** [comment]
image


hmm this has the opposite of what I hope, I'm confused

**Comment by jeremiedb** [comment]
Do you have a reproducible example for the above plots? Was it using MLJ or internal API?
The proposed changes look fine. With internal API, `fit_evotree`, if using `x_eval` / `y_eval` and an error metric, does the logging progress in the expected way?

**Comment by Moelf** [comment]
no, yeah, this seems fine...

```julia
julia> using EvoTrees, LossFunctions

julia> x_train = rand(10^4, 60);

julia> y_train = rand(Bool, size(x_train, 1));

julia> config = EvoTreeRegressor(
               loss=:logistic,
               nrounds=100,
               );

julia> bst = fit_evotree(config; x_train, y_train);

julia> f(ntree_limit) = value(CrossEntropyLoss(), y_train, EvoTrees.predict(bst, x_train; ntree_limit), AggMode.Mean())
f (generic function with 1 method)

julia> [f(x) for x = 1:10:100]
10-element Vector{Float64}:
 0.6930191750979565
 0.680571432099415
 0.668543986221046
 0.6572494599405041
 0.6460836519003692
 0.6355076988701024
 0.6255258685929427
 0.6153140695323568
 0.6058941959712184
 0.5961226511170347
```

**Comment by Moelf** [comment]
oh wait, it is weird when using Classifier:
```julia
julia> config = EvoTreeClassifier(
               nrounds=100,
               );
[ Info: Following 13 arguments were not provided and will be set to default: nbins, alpha, num_class, gamma, max_depth, T, lambda, min_weight, colsample, eta, rng, device, rowsample.

julia> bst = fit_evotree(config; x_train, y_train);

julia> f(ntree_limit) = value(CrossEntropyLoss(), y_train, EvoTrees.predict(bst, x_train; ntree_limit), AggMode.Mean())
f (generic function with 1 method)

julia> [f(x) for x = 1:10:100]
10-element Vector{Float64}:
 0.6931471805599533
 0.6965624247222955
 0.6999197882544534
 0.7032977666648851
 0.707394377330645
 0.711312003652628
 0.7154288676737242
 0.7191722553880523
 0.7231821409095456
 0.7274258634645068
```

**Comment by jeremiedb** [comment]
What's happening is that I hadn't put proper safeguards for bool target. Target was assumed to be either integers pointing to the category level (1 based), or categorical vector. With a bool target, it acts as a 0-based index, which explains the improper behavior. I'll push a quick fix to add a proper handling of book target.

**Comment by jeremiedb** [comment]
The following works fine: 

```julia
config = EvoTreeClassifier(
               nrounds=100,
               );
bst = fit_evotree(config; x_train, y_train, x_eval=x_train, y_eval = y_train, print_every_n=5, metric=:mlogloss);
```

What I think is the issue is that `CrossEntropyLoss()` is expecting a vector while the predictions from a classifier EvoTree model is a `[nobs, num_class]` matrix. For the particular binary case, you could probably do something like: `EvoTrees.predict(bst, x_train; ntree_limit)[:, 2]`

**Comment by Moelf** [comment]
ah yes........ UGH, I think LossFunctions should check if the `size()` are compatible, instead of (what I think they're currently) just iterating the `zip(yhat, y)`...

**Comment by Moelf** [comment]
```julia
julia> f(ntree_limit) = value(CrossEntropyLoss(), y_train, EvoTrees.predict(bst, x_train; ntree_limit)[:, 2], AggMode.Mean())
f (generic function with 1 method)

julia> bst = fit_evotree(config; x_train, y_train);

julia> [f(x) for x = 1:10:100]
10-element Vector{Float64}:
 0.6931471805600649
 0.6702261979644001
 0.650409651427238
 0.6325497430021352
 0.615643554513874
 0.5996608293860044
 0.5857358626327895
 0.5712704073103819
 0.5575557036197865
 0.5448763392255006
```

yeah that's it

**Pull request merged**
